// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using StudentHelp.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace StudentHelp.Data
{
    public partial class StudenthelpContext
    {
        private StudenthelpContextProcedures _procedures;

        public virtual StudenthelpContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new StudenthelpContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public StudenthelpContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public interface IStudenthelpContextProcedures
    {
    }

    public partial class StudenthelpContextProcedures : IStudenthelpContextProcedures
    {
        private readonly StudenthelpContext _context;

        public StudenthelpContextProcedures(StudenthelpContext context)
        {
            _context = context;
        }
    }
}
