// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StudentHelperWebApi.Data.Entities
{
    public partial class Assignment
    {
        public Assignment()
        {
            StudentAssignment = new HashSet<StudentAssignment>();
        }

        public Guid AssignmentId { get; set; }

        public Guid CourseId { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public DateTime AssignedDate { get; set; }

        public DateTime DueDate { get; set; }

        public virtual Course Course { get; set; }
        public virtual ICollection<StudentAssignment> StudentAssignment { get; set; }
    }
}