// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StudentHelperWebApi.Data.Entities
{
    public partial class Course
    {
        public Course()
        {
            Assignment = new HashSet<Assignment>();
            StudentCourse = new HashSet<StudentCourse>();
        }

        public Guid CourseId { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public virtual ICollection<Assignment> Assignment { get; set; }
        public virtual ICollection<StudentCourse> StudentCourse { get; set; }
    }
}