// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StudentHelperWebApi.Data.Entities
{
    public partial class Student
    {
        public Student()
        {
            StudentAssignment = new HashSet<StudentAssignment>();
            StudentCourse = new HashSet<StudentCourse>();
        }

        public Guid StudentId { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }

        public DateTime RegistrationDate { get; set; }

        public virtual ICollection<StudentAssignment> StudentAssignment { get; set; }
        public virtual ICollection<StudentCourse> StudentCourse { get; set; }
    }
}