// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentHelperWebApi.Data.Entities
{
    public partial class StudentAssignment
    {
        public Guid StudentId { get; set; }
        public Guid AssignmentId { get; set; }
        public DateTime? DateSubmitted { get; set; }
        public int? Grade { get; set; }

        public virtual Assignment Assignment { get; set; }
        public virtual Student Student { get; set; }
    }
}