// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentHelp.Models
{
    public partial class Assignment
    {
        public Assignment()
        {
            StudentAssignment = new HashSet<StudentAssignment>();
        }

        public int AssignmentId { get; set; }
        public int CourseId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime AssignedDate { get; set; }
        public DateTime DueDate { get; set; }

        public virtual Course Course { get; set; }
        public virtual ICollection<StudentAssignment> StudentAssignment { get; set; }
    }
}