// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StudentHelp.Models
{
    public partial class Student
    {
        public Student()
        {
            StudentAssignment = new HashSet<StudentAssignment>();
            StudentCourse = new HashSet<StudentCourse>();
        }

        public int StudentId { get; set; }

        [StringLength(50, ErrorMessage = "cannot exceed 50 characters")]
        [Required(ErrorMessage = "is required")]
        public string FirstName { get; set; }

        [StringLength(50, ErrorMessage = "cannot exceed 50 characters")]
        [Required(ErrorMessage = "is required")]
        public string LastName { get; set; }

        [StringLength(60, ErrorMessage = "annot exceed 60 characters")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [Required(ErrorMessage = "is required")]
        public string Email { get; set; }

        [DataType(DataType.Date, ErrorMessage = "please enter a date")]
        public DateTime RegistrationDate { get; set; }

        public virtual ICollection<StudentAssignment> StudentAssignment { get; set; }
        public virtual ICollection<StudentCourse> StudentCourse { get; set; }
    }
}